### ISSUE TITLE
Implement the ability to change the administrator's password.

### ISSUE THREAD

**Issue by kuroda** [oiax/live_reverse_proxy#23]
* Place a “change password” button in the administrators table.
* When this button is clicked, display a form containing the "Password" label and a password field.
* When this form is submitted, update the administrator's `password_hash` if the password is not empty.

**Comment by kkana6624** [comment]
@kuroda 
Let me confirm the specification.

1. I found it natural to place the “Delete” button at the right end of the table. In other words, “Edit” - “Password Change” - “Delete”. Is this order of the buttons OK?
2. Is the form that appears when the “Password Change” button is clicked in the same format as the one that appears when “Edit” is clicked?
3. About the password input form,
Is it necessary to place a re-entry form for the confirmation form?
4. I assume that the password entered in the form will be masked, but do I need a button to unmask it?
5. Should the Password Change form button display “Cancel” - “Update” as in “Edit”?
6. If the password is blank, should there be a warning like “Password is blank”?
7. Should passwords be limited to a certain number or type of characters?

**Comment by kuroda** [comment]
@kkana6624 

1. OK
2. The form should be displayed in a cell in the "Actions" column.
3. No.
4. Yes.
5. "Update Password" is better.
6. "cant'be blank" is OK.
7. No.

「Enter New Password」 ラベルの右に XXX を加えてください。

 `<small>8 characters or more</small>`

Additional comments:

* Add `<small>8 characters or more</small>` to the right of the "Enter New Password" label.
