### ISSUE TITLE
Implement the ability for administrators to change their own passwords

### ISSUE THREAD

**Issue by kuroda** [oiax/live_reverse_proxy#26]
* Replace the text on the "Sign out" button on the far right of the navbar with the name of the administrator who is logged in.
* When the administrator clicks that button, display a drop-down menu below it with the following two items:
  * Change password
  * Sign out
* When the administrator clicks on the menu item "Change password", take him to the URL path `/change_password` and display the following screen:
  * The heading “Change your password”
  * The label “Your current password” and a password entry field
  * The label “Your new password” and a password entry field
  * The "Cancel" button
  * The "Change" button
* Implement the following results when the administrator clicks the “Change” button.
  * If “Your current password” is not correct, an error message “is wrong.
  * If “Your new password” is empty, display the error message “can't be blank.
  * If not, save the administrator's new password in the database and close the form.
* When the administrator clicks on the menu item "Sign out", make him signed out in the same way as before.

**Comment by kkana6624** [comment]
@kuroda 
Let me ask you a question.

* Implemented regarding the UI of each button. Check that the behaviour is in line with the image.
* For materials related to `change_password`, in which directory should they generally be placed?
I thought of the following, but please point out if there are any misconceptions.
  1. Create a `change_password_html` directory under the `/live_web_server_web/controllers` directory and place the `change_password.html.heex` file.
  2. Place `change_password_controller.ex` under the `/live_web_server_web/controllers` directory.

**Comment by kkana6624** [comment]
@kuroda 
Please Reply.

**Comment by kuroda** [comment]
@kkana6624 

> Implemented regarding the UI of each button. Check that the behaviour is in line with the image.

The first item in the drop-down menu (`<span>` displaying the administrator's name) is not required.

> For materials related to change_password, in which directory should they generally be placed?

Here are my assumptions:

* This functionality is implemented using the `AdminLive`, not a controller.
* The path to this functionality is `/change_my_password`.
* Its action name in `AdminLive` is `:change_my_password`.
* The path of its template is `lib/live_web_server_web/live/admin_live/change_my_password.html.heex`.

**Comment by kkana6624** [comment]
@kuroda 
Sorry for the delay in response.
The password change function has been implemented.
Please check that it conforms to the image.

Also, I would like to display a flash message when the password is successfully changed, but I didn't know how to implement it properly, so please let us know.

In addition, I feel that the previous issue was a roundabout implementation, but can you make the implementation a little simpler when using put_flash?

**Comment by kuroda** [comment]
@kkana6624 

Please submit a pull request with a WIP label.
